config/routes.rb
Codepink::Application.routes.draw do

  resources :location_groups
  resources :locations
  resources :users
  resources :publishers
  resources :drone_attacks
  resources :sessions, only: [:new, :create, :destroy]

  root :to => "maps#index"

  match "/tests" => "tests#index"
  match "/signup"  => "users#new"
  match "/admin" => "sessions#new"
  match "/signout" => "sessions#destroy", via: :delete

end

app/models/location_group.rb
class LocationGroup < ActiveRecord::Base
  attr_accessible :name, :xcoordinate, :ycoordinate
  has_many :location, :autosave => true
end

app/controllers/location_groups_controller.rb
class LocationGroupsController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :create, :destroy]

  # GET /location_groups
  # GET /location_groups.json
  def index
    @location_groups = LocationGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @location_groups }
    end
  end

  # GET /location_groups/1
  # GET /location_groups/1.json
  def show
    @location_group = LocationGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location_group }
    end
  end

  # GET /location_groups/new
  # GET /location_groups/new.json
  def new
    @location_group = LocationGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location_group }
    end
  end

  # GET /location_groups/1/edit
  def edit
    @location_group = LocationGroup.find(params[:id])
  end

  # POST /location_groups
  # POST /location_groups.json
  def create
    @location_group = LocationGroup.new(params[:location_group])

    respond_to do |format|
      if @location_group.save
        format.html { redirect_to @location_group, notice: 'Location group was successfully created.' }
        format.json { render json: @location_group, status: :created, location: @location_group }
      else
        format.html { render action: "new" }
        format.json { render json: @location_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /location_groups/1
  # PUT /location_groups/1.json
  def update
    @location_group = LocationGroup.find(params[:id])

    respond_to do |format|
      if @location_group.update_attributes(params[:location_group])
        format.html { redirect_to @location_group, notice: 'Location group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /location_groups/1
  # DELETE /location_groups/1.json
  def destroy
    @location_group = LocationGroup.find(params[:id])
    @location_group.destroy

    respond_to do |format|
      format.html { redirect_to location_groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/location_groups_helper.rb
module LocationGroupsHelper
end

app/views/location_groups/_form.html.erb
<%= form_for(@location_group) do |f| %>
    <% if @location_group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@location_group.errors.count, "error") %> prohibited this location_group from being saved:</h2>

          <ul>
            <% @location_group.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :xcoordinate %><br />
      <%= f.text_field :xcoordinate %>
    </div>
    <div class="field">
      <%= f.label :ycoordinate %><br />
      <%= f.text_field :ycoordinate %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/location_groups/edit.html.erb
<h1>Editing location_groups</h1>

<%= render 'form' %>

<%= link_to 'Show', @location_group %> |
<%= link_to 'Back', location_groups_path %>

app/views/location_groups/index.html.erb
<h1>Listing location_groups</h1>
<%= link_to 'Create New location_group', new_location_group_path %><br/>
<table>
  <tr>
    <th>Name</th>
    <th>X-Coordinate</th>
    <th>Y-Coordinate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @location_groups.each do |location_group| %>
      <tr>
        <td><%= location_group.name %></td>
        <td><%= location_group.xcoordinate %></td>
        <td><%= location_group.ycoordinate %></td>
        <td><%= link_to 'Edit', edit_location_group_path(location_group) %></td>
        <td><%= link_to 'Destroy', location_group, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
  <% end %>
</table>

<br />

app/views/location_groups/new.html.erb
<h1>Create A New Location Group</h1>

<%= render 'form' %>

<%= link_to 'Locations', locations_path %>

app/views/location_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location_group.name %>
</p>
<p>
  <b>X-Coordinate:</b>
  <%= @location_group.xcoordinate %>
</p>
<p>
  <b>Y-Coordinate:</b>
  <%= @location_group.ycoordinate %>
</p>

<%= link_to 'Locations', locations_path %>