config/routes.rb
Codepink::Application.routes.draw do

  resources :location_groups
  resources :locations
  resources :users
  resources :publishers
  resources :drone_attacks
  resources :sessions, only: [:new, :create, :destroy]

  root :to => "maps#index"

  match "/tests" => "tests#index"
  match "/signup"  => "users#new"
  match "/admin" => "sessions#new"
  match "/signout" => "sessions#destroy", via: :delete

end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :reference_link, :autosave => true
  attr_accessible :name
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :create, :destroy]

  # GET /publishers
  # GET /publishers.json
  def index
    @publishers = Publisher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publishers }
    end
  end
  # GET /publishers/1
  # GET /publishers/1.json
  def show
    @publisher = Publisher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publisher }
    end
  end

  # GET /publishers/new
  # GET /publishers/new.json
  def new
    @publisher = Publisher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publisher }
    end
  end

  # GET /publishers/1/edit
  def edit
    @publisher = Publisher.find(params[:id])
  end

  # POST /publishers
  # POST /publishers.json
  def create
    @publisher = Publisher.new(params[:publisher])

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to @publisher, notice: 'publisher was successfully created.' }
        format.json { render json: @publisher, status: :created, publisher: @publisher }
      else
        format.html { render action: "new" }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /publishers/1
  # PUT /publishers/1.json
  def update
    @publisher = Publisher.find(params[:id])

    respond_to do |format|
      if @publisher.update_attributes(params[:publisher])
        format.html { redirect_to @publisher, notice: 'publisher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy

    respond_to do |format|
      format.html { redirect_to publishers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/_form.html.erb
<%= form_for(@publisher) do |f| %>
    <% if @publisher.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

          <ul>
            <% @publisher.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/publishers/edit.html.erb
<h1>Editing publishers</h1>

<%= render 'form' %>

<%= link_to 'Show', @publisher %> |
<%= link_to 'Back', publishers_path %>

app/views/publishers/index.html.erb
<h1>Listing publishers</h1>
<%= link_to 'Create New Publisher', new_publisher_path %><br/>
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @publishers.each do |publisher| %>
      <tr>
        <td><%= publisher.name %></td>
        <td><%= link_to 'Edit', edit_publisher_path(publisher) %></td>
        <td><%= link_to 'Destroy', publisher, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
  <% end %>
</table>

<br />

app/views/publishers/new.html.erb
<h1>Create A New Publisher</h1>

<%= render 'form' %>

<%= link_to 'Back', publishers_path %>

app/views/publishers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>City:</b>
  <%= @publisher.name %>
</p>

<%= link_to 'Edit', edit_publisher_path(@publisher) %> |
<%= link_to 'Back', publishers_path %>