config/routes.rb
Codepink::Application.routes.draw do

  resources :location_groups
  resources :locations
  resources :users
  resources :publishers
  resources :drone_attacks
  resources :sessions, only: [:new, :create, :destroy]

  root :to => "maps#index"

  match "/tests" => "tests#index"
  match "/signup"  => "users#new"
  match "/admin" => "sessions#new"
  match "/signout" => "sessions#destroy", via: :delete

end

app/models/drone_attack.rb
require  Rails.root.to_s + "/app/helpers/drone_attacks_helper.rb"
include DroneAttacksHelper


class DroneAttack < ActiveRecord::Base

  attr_accessible :al_qaida_max, :al_qaida_min, :reference_links_attributes, :location_group_attributes, :publisher_id, :publishers_attributes, :city, :civilians_max, :civilians_min, :display_date, :forigeners_max, :forigeners_min, :incident_date, :incident_year, :injured_max, :injured_min, :location, :province, :taliban_max, :taliban_min, :total_died_max, :total_died_min, :women, :latitude, :longitude, :reference_links, :xcoordinate, :ycoordinate, :location_id, :location_group
  has_many :reference_links, :autosave => true
  has_many :publishers, :through => :reference_links
  belongs_to :location
  has_one :location_group, :through => :location

  accepts_nested_attributes_for :reference_links
  accepts_nested_attributes_for :location
  accepts_nested_attributes_for :publishers
  accepts_nested_attributes_for :location_group

  def refresh_db
    drone_attack = DroneAttacksHelper.new
    end
end

app/controllers/drone_attacks_controller.rb
class DroneAttacksController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :create, :destroy]

  # GET /drone_attacks
  # GET /drone_attacks.json
  def index
    @drone_attacks = DroneAttack.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :layout => 'blank'}
    end
  end

  # GET /drone_attacks/1
  # GET /drone_attacks/1.json
  def show
    @drone_attack = DroneAttack.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :layout => 'blank' }
    end
  end

  # GET /drone_attacks/new
  # GET /drone_attacks/new.json
  def new
    @drone_attack = DroneAttack.new
    @drone_attack.reference_links.build

    #respond_to do |format|
    #  format.html
    #end
  end

  # GET /drone_attacks/1/edit
  def edit
    @drone_attack = DroneAttack.find(params[:id])
  end

  # POST /drone_attacks
  # POST /drone_attacks.json
  def create
    @drone_attack = DroneAttack.new(params[:drone_attack])

    respond_to do |format|
      if @drone_attack.save
        format.html { redirect_to @drone_attack, notice: 'Drone attack was successfully created.' }
        format.json { render json: @drone_attack, status: :created, location: @drone_attack }
      else
        format.html { render action: "new" }
        format.json { render json: @drone_attack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /drone_attacks/1
  # PUT /drone_attacks/1.json
  def update
    @drone_attack = DroneAttack.find(params[:id])

    respond_to do |format|
      if @drone_attack.update_attributes(params[:drone_attack])
        format.html { redirect_to @drone_attack, notice: 'Drone attack was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @drone_attack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drone_attacks/1
  # DELETE /drone_attacks/1.json
  def destroy
    @drone_attack = DroneAttack.find(params[:id])
    @drone_attack.destroy

    respond_to do |format|
      format.html { redirect_to drone_attacks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/drone_attacks_helper.rb
require 'httparty'
require 'json'
require 'geokit'

include GeoKit::Geocoders

module DroneAttacksHelper
  class DroneAttackHelper



    def create_drone_attack_from_json(attackData)
      droneAttack = DroneAttack.new

      province =  update_name(attackData["province"].downcase)
      city = update_name(attackData["city"].downcase)
      information = attackData["location"]

      reference_location = Location.where(:city => city, :province => province, :information => information).first
      if reference_location.nil?
        location = create_location(city, province, information)
        droneAttack.location= location
      else
        droneAttack.location= reference_location
      end
      droneAttack.al_qaida_min= attackData["al_qaida_min"]
      droneAttack.al_qaida_max= attackData["al_qaida_max"]
      droneAttack.taliban_min= attackData["taliban_min"]
      droneAttack.taliban_max= attackData["taliban_max"]
      droneAttack.civilians_min= attackData["civilians_min"]
      droneAttack.civilians_max= attackData["civilians_max"]
      droneAttack.forigeners_min= attackData["forigeners_min"]
      droneAttack.forigeners_max= attackData["forigeners_max"]
      droneAttack.total_died_min= attackData["total_died_min"]
      droneAttack.total_died_max= attackData["total_died_max"]
      droneAttack.injured_min= attackData["injured_min"]
      droneAttack.injured_max= attackData["injured_max"]
      droneAttack.women= attackData["women"]
      droneAttack.incident_year= attackData["incident_year"]
      droneAttack.incident_date= attackData["incident_date"].to_i
      droneAttack.display_date= attackData["display_date"]
      references = attackData["refrences"]
      if !references.nil?
        references.each do |ref|
          ref_link = create_reference_link(ref)
          droneAttack.reference_links << ref_link
        end
      end

      return droneAttack
    end

    def create_publisher(raw_data)
      name = raw_data["name"]
      name_in_db = Publisher.where(:name => name ).first
      if name_in_db.nil?
        publisher = Publisher.create(:name => name)
      else
        publisher = name_in_db
      end
      return publisher
    end

    def create_reference_link(raw_data)
      publisher = create_publisher(raw_data)
      rl = ReferenceLink.create(:url => raw_data["url"], :publisher => publisher)

      return rl
    end

    def create_location(city, province, information)
      location = Location.where(:city => city, :province => province, :information => information ).first
      location_close = Location.where(:city => city, :province => province)
      if !location.nil?
        location_group = location.location_group
      elsif location.nil? & !location_close.nil?
        location_group = LocationGroup.create(:name => city + "-" + province + location_close.count.to_s,
                                              :xcoordinate => Random.rand(1...700), :ycoordinate => Random.rand(1...250))
      elsif location.nil? & location_close.nil?
        location_group = LocationGroup.create(:name => city + "-" + province,
                                              :xcoordinate => Random.rand(1...700), :ycoordinate => Random.rand(200...500))
      else
        location_group = LocationGroup.create(:name => city + "-" + province + "?",
                                              :xcoordinate => Random.rand(1...700), :ycoordinate => Random.rand(500...800))
      end
      location = Location.create(:city => city, :province => province, :location_group => location_group, :information => information)
      return location
    end

    def update_name(name)
      name.downcase
      name.gsub(" ", "_")
    end
  end
end

app/views/drone_attacks/_form.html.erb
<%= form_for(@drone_attack) do |f| %>
    <%= f.fields_for :location do |builder|  %>
        <p>
          <%= builder.label :city %><br />
          <%= builder.text_field :city %>
        </p>

        <p>
          <%= builder.label :location_group, "Location Group" %><br/>
          <%= builder.collection_select(:location_group_id, LocationGroup.all, :id, :name) %>
        </p>
    <% end %>
    <p>
      <%= f.label :incident_year %><br />
      <%= f.text_field :incident_year %>
    </p>
    <p>
      <%= f.label :incident_date %><br />
      <%= f.text_field :incident_date %>
    </p>
    <p>
      <%= f.label :display_date %><br />
      <%= f.text_field :display_date %>
    </p>
    <p>
      <%= f.label :location %><br />
      <%= f.collection_select(:location_id, Location.all, :id, :city) %>
    </p>
    <p>
      <%= f.label :al_qaida_min %><br />
      <%= f.text_field :al_qaida_min %>
    </p>
    <p>
      <%= f.label :al_qaida_max %><br />
      <%= f.text_field :al_qaida_max %>
    </p>
    <p>
      <%= f.label :taliban_min %><br />
      <%= f.text_field :taliban_min %>
    </p>
    <p>
      <%= f.label :taliban_max %><br />
      <%= f.text_field :taliban_max %>
    </p>
    <p>
      <%= f.label :civilians_min %><br />
      <%= f.text_field :civilians_min %>
    </p>
    <p>
      <%= f.label :civilians_max %><br />
      <%= f.text_field :civilians_max %>
    </p>
    <p>
      <%= f.label :forigeners_min %><br />
      <%= f.text_field :forigeners_min %>
    </p>
    <p>
      <%= f.label :forigeners_max %><br />
      <%= f.text_field :forigeners_max %>
    </p>
    <p>
      <%= f.label :total_died_min %><br />
      <%= f.text_field :total_died_min %>
    </p>
    <p>
      <%= f.label :total_died_max %><br />
      <%= f.text_field :total_died_max %>
    </p>
    <p>
      <%= f.label :injured_min %><br />
      <%= f.text_field :injured_min %>
    </p>
    <p>
      <%= f.label :injured_max %><br />
      <%= f.text_field :injured_max %>
    </p>
    <p>
      <%= f.label :women %><br />
      <%= f.check_box :women %>
    </p>
    <%= f.fields_for :reference_links do |builder|  %>
    <p>
      <%= builder.label :url, "URL" %><br/>
      <%= builder.text_field :url %>
    </p>
    <p>
      <%= builder.label :publisher, "Publisher" %><br/>
      <%= builder.collection_select(:publisher_id, Publisher.all, :id, :name) %>
    </p>

    <% end %>
    <p><%= f.submit  %></p>
<% end %>

app/views/drone_attacks/_update_location.html.erb
<%= form_for(@drone_attack) do |f| %>
    <% if @drone_attack.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@drone_attack.errors.count, "error") %> prohibited this drone_attack from being saved:</h2>

          <ul>
            <% @drone_attack.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <h3>ID: <%= @drone_attack.id %></h3>
    <h3>City: <%= @drone_attack.location.city %></h3>
    <h3>Province: <%= @drone_attack.location.province %></h3>
    <h3>Information: <%= @drone_attack.location.information %></h3>

    <div class="field">
      <%= f.label :location %><br />
      <%= f.collection_select(:location_id, Location.all, :id, :city) %>
    </div>
    <%= f.fields_for :location do |builder|  %>
        <p>
          <%= builder.label :location_group, "Location Group" %><br/>
          <%= builder.collection_select(:location_group_id, LocationGroup.all, :id, :name) %>
        </p>

    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/drone_attacks/edit.html.erb
<h1>Edit Drone Attack Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @drone_attack %> |
<%= link_to 'Back', drone_attacks_path %>

app/views/drone_attacks/index.html.erb
<h1>Listing drone_attacks</h1>

<div><%= link_to 'Create New Drone Attack', new_drone_attack_path %></div>
</br>

<table>
  <tr>
    <th>Id</th>
    <th>City</th>
    <th>Province</th>
    <th>LocationInfo</th>
    <th>LocationGroup</th>
    <th>X-Coordinate</th>
    <th>Y-Coordinate</th>
    <th></th>
  </tr>

  <% @drone_attacks.each do |drone_attack| %>
      <tr>
        <td><%= drone_attack.id %></td>
        <td><%= drone_attack.location.city %></td>
        <td><%= drone_attack.location.province %></td>
        <td><%= drone_attack.location.information %></td>
        <td><%= drone_attack.location.location_group.name %></td>
        <td><%= drone_attack.location.location_group.xcoordinate %></td>
        <td><%= drone_attack.location.location_group.ycoordinate %></td>
        <td><%= link_to 'Edit Location', edit_location_path(drone_attack.location) %></td>
        <td><%= link_to 'Delete', drone_attack, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
  <% end %>
</table>

<br />

app/views/drone_attacks/index.html.haml
%h1 Drone Attacks in Pakistan

#map-container
    #map

#inline-actions
    %span Max zoom level:
    %select{:id=>"zoom"}
        %option{:value=>"-1"} Default
        %option{:value=>"7"} 7
        %option{:value=>"8"} 8
        %option{:value=>"9"} 9
        %option{:value=>"10"} 10
        %option{:value=>"11"} 11
        %option{:value=>"12"} 12
        %option{:value=>"13"} 13
        %option{:value=>"14"} 14
    %span.item Cluster size:
    %select{:id=>"size"}
        %option{:value=>"-1"} Default
        %option{:value=>"40"} 40
        %option{:value=>"50"} 50
        %option{:value=>"70"} 70
        %option{:value=>"80"} 80
    %span.item Cluster size:
    %select{:id=>"style"}
        %option{:value=>"-1"} Default
        %option{:value=>"0"} People
        %option{:value=>"1"} Conversation
        %option{:value=>"2"} Heart

    %input#refresh{:type=>"button", :value=>"Refresh Map", :class=>"item"}
    %a#clear{:href=>"#"} Clear

%p hello
    

app/views/drone_attacks/new.html.erb
<h1>Create A New Drone Attack</h1>

<%= render 'form' %>

<%= link_to 'Back', drone_attacks_path %>

app/views/drone_attacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @drone_attack.id %>
</p>

<p>
  <b>City:</b>
  <%= @drone_attack.location.city %>
</p>

<p>
  <b>Province:</b>
  <%= @drone_attack.location.province %>
</p>

<p>
  <b>Xcoord:</b>
  <%= @drone_attack.location.location_group.xcoordinate %>
</p>

<p>
  <b>Ycoord:</b>
  <%= @drone_attack.location.location_group.ycoordinate %>
</p>


<%= link_to 'Edit', edit_drone_attack_path(@drone_attack) %>
<%= link_to 'Back', drone_attacks_path %>