config/routes.rb
Codepink::Application.routes.draw do

  resources :location_groups
  resources :locations
  resources :users
  resources :publishers
  resources :drone_attacks
  resources :sessions, only: [:new, :create, :destroy]

  root :to => "maps#index"

  match "/tests" => "tests#index"
  match "/signup"  => "users#new"
  match "/admin" => "sessions#new"
  match "/signout" => "sessions#destroy", via: :delete

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :city, :province, :xcoordinate, :ycoordinate, :information, :location_group, :location_group_id, :location_group_attributes
  has_many :drone_attacks
  belongs_to :location_group
  accepts_nested_attributes_for :location_group
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :create, :destroy]
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
    <% if @location.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

          <ul>
            <% @location.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :city %><br />
      <%= f.text_field :city %>
    </div>
    <div class="field">
      <%= f.label :province %><br />
      <%= f.text_field :province %>
    </div>
    <div class="field">
      <%= f.label :information %><br />
      <%= f.text_field :information %>
    </div>
    <div>
      <%= f.label :location_group %><br />
      <%= f.collection_select(:location_group_id, LocationGroup.all, :id, :name) %>

    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Locations</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %> |
<%= link_to 'Create New Location Group', new_location_group_path %><br/>

app/views/locations/index.html.erb
<%= render 'layouts/header' %>
<h1>Listing Locations</h1>

<table>
  <tr>
    <th>City</th>
    <th>Province</th>
    <th>Information</th>
    <th>Location Group</th>
    <th>X-Coordinate</th>
    <th>Y-Coordinate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @locations.each do |location| %>
      <tr>
        <td><%= location.city %></td>
        <td><%= location.province %></td>
        <td><%= location.information %></td>
        <td><%= location.location_group.name %></td>
        <td><%= location.location_group.xcoordinate %></td>
        <td><%= location.location_group.ycoordinate %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>Create A New Location</h1>

<%= render 'form' %>

<%= link_to 'Locations', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>City:</b>
  <%= @location.city %>
</p>

<p>
  <b>Province:</b>
  <%= @location.province %>
</p>

<p>
  <b>Information:</b>
  <%= @location.information %>
</p>

<p>
  <b>X-Coordinate:</b>
  <%= @location.location_group.xcoordinate %>
</p>

<p>
  <b>Y-Coordinate:</b>
  <%= @location.location_group.ycoordinate %>
</p>


<%= link_to 'Locations', locations_path %>